services:
  todoapp:
    image: todoapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres_db2;Port=5432;Database=ToDoDB;Username=postgres;Password=3568;"
    ports:
      - "7147:8080"
    depends_on:
      - postgres_db2

  postgres_db2:
    container_name: postgres_db2
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3568
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data: